version: '3'
 
services:
  wp: 
    image: wordpress:latest 
    ports:
      - 85:80
    environment:
      - WORDPRESS_DB_HOST: db
      - WORDPRESS_DB_NAME: wordpress
      - WORDPRESS_DB_USER: root
      - WORDPRESS_DB_PASSWORD: mypassword
  db: 
    image: mysql:latest
    environment:
      - MYSQL_DATABASE: wordpress
      - MYSQL_ROOT_PASSWORD: mypassword